### ISSUE TITLE
Add a special rule for `late_pen`: Show 🔥 rather than ✅ .

### ISSUE THREAD

**Issue by yyjlincoln** [TommyZhang-z/unsw-cse-pretty-sturec#3]
This will greatly help improve the readability of `sturec`, as `0/5` is the *ideal mark* for `late_pen`, rather than 5/5.

**Comment by TommyZhang-z** [comment]
I did thought abt this, but I am not sure how the tutor is going to name there test names. I haven't take 1511 so I am not too sure abt their naming convention.
I am currently taking 1521 and 2521, and 1521 doesn't even have a late_pen field. So I am not sure if its gonna work for all courses.
