### ISSUE TITLE
Consistent code style by using `.editorconfig`?

### ISSUE THREAD

**Issue by yyjlincoln** [TommyZhang-z/unsw-cse-pretty-sturec#6]
Hi, 

I'm wondering if we should use something like `.editorconfig` so we can make sure our styles are consistent (or just for the sake of it)?

**Comment by TommyZhang-z** [comment]
yea sure, I am switching between vscode and pycharm so my code styles are not consitent already, and yea we should definately have a shared style guide😂

maybe we can use?:
https://github.com/microsoft/vscode-python/blob/main/.editorconfig

I guess I will commit the  .editorconfig file shortly



and I should prob update README.md sometime during the weekend
